require:
  - rubocop-performance
  - rubocop-rspec

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

AllCops:
  NewCops: enable
  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
  <% end %>
